#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# Bootstrap Script for @markoradak/color-picker
# ============================================================================
#
# A compound-component React color picker + gradient picker library.
#
# This script will:
#   - Check prerequisites (Node.js 18+, pnpm)
#   - Initialize pnpm workspace monorepo with Turborepo
#   - Scaffold packages/react/ (the component library)
#   - Scaffold apps/web/ (Next.js demo/docs site)
#   - Install all dependencies
#   - Generate configuration files (TypeScript, tsup, Tailwind, etc.)
#   - Create placeholder source files with proper structure
#   - Verify the build pipeline works
#
# Generated by Claude Code /bootstrap command
# ============================================================================

# -- Colors & Utilities -------------------------------------------------------

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

info()    { echo -e "${BLUE}i${NC} $1"; }
success() { echo -e "${GREEN}+${NC} $1"; }
warn()    { echo -e "${YELLOW}!${NC} $1"; }
error()   { echo -e "${RED}x${NC} $1"; exit 1; }
header()  { echo -e "\n${BOLD}$1${NC}"; }

# -- Prerequisite Checks ------------------------------------------------------

check_node() {
  if ! command -v node &> /dev/null; then
    error "Node.js is not installed. Please install Node.js 18+ first."
  fi

  NODE_VERSION=$(node -v | cut -d'.' -f1 | sed 's/v//')
  if [ "$NODE_VERSION" -lt 18 ]; then
    error "Node.js 18+ is required. Current version: $(node -v)"
  fi
  success "Node.js $(node -v) detected"
}

check_pnpm() {
  if ! command -v pnpm &> /dev/null; then
    error "pnpm is not installed. Install it with: npm install -g pnpm"
  fi
  success "pnpm $(pnpm -v) detected"
}

# -- Root Workspace Config -----------------------------------------------------

create_root_package_json() {
  if [ -f package.json ]; then
    warn "package.json already exists, skipping"
    return
  fi

  info "Creating root package.json..."
  cat > package.json <<'ROOTPKG'
{
  "name": "color-picker-monorepo",
  "private": true,
  "scripts": {
    "dev": "turbo dev",
    "build": "turbo build",
    "test": "turbo test",
    "lint": "turbo lint",
    "clean": "turbo clean",
    "typecheck": "turbo typecheck"
  },
  "packageManager": "pnpm@10.18.3",
  "engines": {
    "node": ">=18.0.0"
  }
}
ROOTPKG
  success "Created root package.json"
}

create_pnpm_workspace() {
  if [ -f pnpm-workspace.yaml ]; then
    warn "pnpm-workspace.yaml already exists, skipping"
    return
  fi

  info "Creating pnpm-workspace.yaml..."
  cat > pnpm-workspace.yaml <<'WORKSPACE'
packages:
  - "packages/*"
  - "apps/*"
WORKSPACE
  success "Created pnpm-workspace.yaml"
}

create_npmrc() {
  if [ -f .npmrc ]; then
    warn ".npmrc already exists, skipping"
    return
  fi

  info "Creating .npmrc..."
  cat > .npmrc <<'NPMRC'
auto-install-peers=true
strict-peer-dependencies=false
NPMRC
  success "Created .npmrc"
}

create_turbo_json() {
  if [ -f turbo.json ]; then
    warn "turbo.json already exists, skipping"
    return
  fi

  info "Creating turbo.json..."
  cat > turbo.json <<'TURBO'
{
  "$schema": "https://turbo.build/schema.json",
  "tasks": {
    "build": {
      "dependsOn": ["^build"],
      "outputs": ["dist/**", ".next/**"]
    },
    "dev": {
      "cache": false,
      "persistent": true
    },
    "test": {
      "dependsOn": ["^build"]
    },
    "lint": {},
    "typecheck": {
      "dependsOn": ["^build"]
    },
    "clean": {
      "cache": false
    }
  }
}
TURBO
  success "Created turbo.json"
}

create_root_tsconfig() {
  if [ -f tsconfig.json ]; then
    warn "Root tsconfig.json already exists, skipping"
    return
  fi

  info "Creating root tsconfig.json..."
  cat > tsconfig.json <<'TSCONFIG'
{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noUncheckedIndexedAccess": true,
    "skipLibCheck": true,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "jsx": "react-jsx"
  },
  "exclude": ["node_modules", "dist", ".next", ".turbo"]
}
TSCONFIG
  success "Created root tsconfig.json"
}

create_gitignore() {
  if [ -f .gitignore ]; then
    warn ".gitignore already exists, skipping"
    return
  fi

  info "Creating .gitignore..."
  cat > .gitignore <<'GITIGNORE'
# Dependencies
node_modules/

# Build outputs
dist/
.next/
out/

# Turbo
.turbo/

# Environment
.env
.env.local
.env.*.local

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# Testing
coverage/

# Package manager
*.tgz
GITIGNORE
  success "Created .gitignore"
}

# -- Library Package (packages/react/) ----------------------------------------

scaffold_library() {
  header "Scaffolding packages/react/ (library)..."

  mkdir -p packages/react/src/{components,hooks,utils}

  # package.json
  if [ ! -f packages/react/package.json ]; then
    info "Creating packages/react/package.json..."
    cat > packages/react/package.json <<'LIBPKG'
{
  "name": "@markoradak/color-picker",
  "version": "0.0.1",
  "description": "A compound-component React color picker and gradient editor",
  "license": "MIT",
  "type": "module",
  "main": "./dist/index.cjs",
  "module": "./dist/index.js",
  "types": "./dist/index.d.ts",
  "exports": {
    ".": {
      "import": {
        "types": "./dist/index.d.ts",
        "default": "./dist/index.js"
      },
      "require": {
        "types": "./dist/index.d.cts",
        "default": "./dist/index.cjs"
      }
    },
    "./presets": {
      "import": {
        "types": "./dist/presets.d.ts",
        "default": "./dist/presets.js"
      },
      "require": {
        "types": "./dist/presets.d.cts",
        "default": "./dist/presets.cjs"
      }
    }
  },
  "files": [
    "dist",
    "README.md"
  ],
  "sideEffects": false,
  "scripts": {
    "build": "tsup",
    "dev": "tsup --watch",
    "test": "vitest run",
    "test:watch": "vitest",
    "typecheck": "tsc --noEmit",
    "clean": "rm -rf dist",
    "prepublishOnly": "pnpm build"
  },
  "peerDependencies": {
    "react": ">=18.0.0",
    "react-dom": ">=18.0.0"
  },
  "dependencies": {
    "colord": "^2.9.3",
    "@radix-ui/react-popover": "^1.1.6"
  },
  "devDependencies": {
    "@testing-library/react": "^16.3.0",
    "@testing-library/jest-dom": "^6.6.3",
    "@types/react": "^19.0.0",
    "@types/react-dom": "^19.0.0",
    "jsdom": "^26.0.0",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "tsup": "^8.4.0",
    "typescript": "^5.7.0",
    "vitest": "^3.0.0"
  },
  "keywords": [
    "react",
    "color-picker",
    "gradient",
    "color",
    "compound-component",
    "radix",
    "tailwindcss"
  ],
  "repository": {
    "type": "git",
    "url": "https://github.com/markoradak/color-picker"
  }
}
LIBPKG
    success "Created packages/react/package.json"
  fi

  # tsconfig.json
  if [ ! -f packages/react/tsconfig.json ]; then
    info "Creating packages/react/tsconfig.json..."
    cat > packages/react/tsconfig.json <<'LIBTS'
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "./dist",
    "rootDir": "./src",
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["src/**/*.ts", "src/**/*.tsx"],
  "exclude": ["node_modules", "dist", "**/*.test.ts", "**/*.test.tsx"]
}
LIBTS
    success "Created packages/react/tsconfig.json"
  fi

  # tsup.config.ts
  if [ ! -f packages/react/tsup.config.ts ]; then
    info "Creating packages/react/tsup.config.ts..."
    cat > packages/react/tsup.config.ts <<'TSUP'
import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    presets: "src/components/presets.tsx",
  },
  format: ["esm", "cjs"],
  dts: true,
  sourcemap: true,
  clean: true,
  external: ["react", "react-dom"],
  treeshake: true,
  splitting: true,
  minify: false,
});
TSUP
    success "Created packages/react/tsup.config.ts"
  fi

  # vitest.config.ts
  if [ ! -f packages/react/vitest.config.ts ]; then
    info "Creating packages/react/vitest.config.ts..."
    cat > packages/react/vitest.config.ts <<'VITEST'
import { defineConfig } from "vitest/config";
import { resolve } from "path";

export default defineConfig({
  test: {
    environment: "jsdom",
    globals: true,
    setupFiles: ["./src/test-setup.ts"],
    include: ["src/**/*.test.{ts,tsx}"],
  },
  resolve: {
    alias: {
      "@": resolve(__dirname, "./src"),
    },
  },
});
VITEST
    success "Created packages/react/vitest.config.ts"
  fi

  # Test setup
  if [ ! -f packages/react/src/test-setup.ts ]; then
    info "Creating packages/react/src/test-setup.ts..."
    cat > packages/react/src/test-setup.ts <<'TESTSETUP'
import "@testing-library/jest-dom/vitest";
TESTSETUP
    success "Created packages/react/src/test-setup.ts"
  fi

  # -- Source Files --

  # types.ts
  if [ ! -f packages/react/src/types.ts ]; then
    info "Creating packages/react/src/types.ts..."
    cat > packages/react/src/types.ts <<'TYPES'
/**
 * A solid color string in HEX, RGB, or HSL format.
 * Examples: "#ff0000", "rgb(255, 0, 0)", "hsl(0, 100%, 50%)"
 */
export type SolidColor = string;

/**
 * Supported color format identifiers.
 */
export type ColorFormat = "hex" | "rgb" | "hsl";

/**
 * A single gradient stop with position and optional 2D coordinates (for mesh gradients).
 */
export interface GradientStop {
  id: string;
  color: string;
  position: number; // 0-100
  x?: number; // mesh only, 0-100
  y?: number; // mesh only, 0-100
}

/**
 * Structured representation of a CSS gradient.
 */
export interface GradientValue {
  type: "linear" | "radial" | "conic" | "mesh";
  stops: GradientStop[];
  angle?: number; // degrees, for linear and conic
  centerX?: number; // 0-100, for radial and conic
  centerY?: number; // 0-100, for radial and conic
}

/**
 * The unified value type for the color picker.
 * Either a solid color string or a structured gradient object.
 */
export type ColorPickerValue = SolidColor | GradientValue;

/**
 * Props for the root ColorPicker component.
 */
export interface ColorPickerProps {
  /** Controlled value */
  value?: ColorPickerValue;
  /** Callback fired when the value changes */
  onValueChange?: (value: ColorPickerValue) => void;
  /** Default value for uncontrolled mode */
  defaultValue?: ColorPickerValue;
  /** Whether the picker is disabled */
  disabled?: boolean;
  /** Children (compound components) */
  children: React.ReactNode;
}

/**
 * Props for the ColorPicker.Area component.
 */
export interface ColorPickerAreaProps {
  className?: string;
}

/**
 * Props for slider components (Hue, Alpha).
 */
export interface ColorPickerSliderProps {
  className?: string;
  orientation?: "horizontal" | "vertical";
}

/**
 * Props for the ColorPicker.Input component.
 */
export interface ColorPickerInputProps {
  className?: string;
}

/**
 * Props for the ColorPicker.Swatches component.
 */
export interface ColorPickerSwatchesProps {
  colors: string[];
  columns?: number;
  className?: string;
}

/**
 * Props for the ColorPicker.Trigger component.
 */
export interface ColorPickerTriggerProps {
  className?: string;
  asChild?: boolean;
  children?: React.ReactNode;
}

/**
 * Props for the ColorPicker.Content component.
 */
export interface ColorPickerContentProps {
  className?: string;
  side?: "top" | "right" | "bottom" | "left";
  align?: "start" | "center" | "end";
  sideOffset?: number;
  children: React.ReactNode;
}

/**
 * HSVA color representation for internal state management.
 * Using HSV avoids rounding issues during drag interactions.
 */
export interface HSVA {
  h: number; // 0-360
  s: number; // 0-100
  v: number; // 0-100
  a: number; // 0-1
}
TYPES
    success "Created packages/react/src/types.ts"
  fi

  # utils/color.ts
  if [ ! -f packages/react/src/utils/color.ts ]; then
    info "Creating packages/react/src/utils/color.ts..."
    cat > packages/react/src/utils/color.ts <<'COLORUTIL'
import { colord, extend } from "colord";
import namesPlugin from "colord/plugins/names";
import a11yPlugin from "colord/plugins/a11y";
import type { ColorFormat, HSVA } from "../types";

// Register colord plugins
extend([namesPlugin, a11yPlugin]);

export { colord };

/**
 * Parse any supported color string into a colord instance.
 */
export function parseColor(input: string) {
  return colord(input);
}

/**
 * Format a color string into the specified format.
 */
export function formatColor(input: string, format: ColorFormat): string {
  const c = colord(input);
  switch (format) {
    case "hex":
      return c.alpha() < 1 ? c.toHex() : c.toHex();
    case "rgb":
      return c.toRgbString();
    case "hsl":
      return c.toHslString();
    default:
      return c.toHex();
  }
}

/**
 * Detect the format of a color string.
 */
export function detectFormat(input: string): ColorFormat {
  const trimmed = input.trim().toLowerCase();
  if (trimmed.startsWith("rgb")) return "rgb";
  if (trimmed.startsWith("hsl")) return "hsl";
  return "hex";
}

/**
 * Check if a string is a valid color.
 */
export function isValidColor(input: string): boolean {
  return colord(input).isValid();
}

/**
 * Convert a color string to HSVA for internal state.
 */
export function toHSVA(input: string): HSVA {
  const c = colord(input);
  const hsv = c.toHsv();
  return {
    h: hsv.h,
    s: hsv.s,
    v: hsv.v,
    a: c.alpha(),
  };
}

/**
 * Convert HSVA values back to a hex string.
 */
export function fromHSVA(hsva: HSVA): string {
  return colord({ h: hsva.h, s: hsva.s, v: hsva.v }).alpha(hsva.a).toHex();
}

/**
 * Determine whether black or white text has better contrast against a background.
 */
export function getContrastColor(bg: string): "black" | "white" {
  return colord(bg).isLight() ? "black" : "white";
}
COLORUTIL
    success "Created packages/react/src/utils/color.ts"
  fi

  # utils/gradient.ts
  if [ ! -f packages/react/src/utils/gradient.ts ]; then
    info "Creating packages/react/src/utils/gradient.ts..."
    cat > packages/react/src/utils/gradient.ts <<'GRADUTIL'
import type { GradientStop, GradientValue } from "../types";

let stopIdCounter = 0;

/**
 * Generate a unique ID for a gradient stop.
 */
function generateStopId(): string {
  return `stop-${++stopIdCounter}-${Date.now().toString(36)}`;
}

/**
 * Create a new gradient stop.
 */
export function createGradientStop(
  color: string,
  position: number
): GradientStop {
  return {
    id: generateStopId(),
    color,
    position: Math.max(0, Math.min(100, position)),
  };
}

/**
 * Sort stops by position (ascending).
 */
export function sortStops(stops: GradientStop[]): GradientStop[] {
  return [...stops].sort((a, b) => a.position - b.position);
}

/**
 * Add a stop to a gradient.
 */
export function addStop(
  gradient: GradientValue,
  color: string,
  position: number
): GradientValue {
  return {
    ...gradient,
    stops: sortStops([...gradient.stops, createGradientStop(color, position)]),
  };
}

/**
 * Remove a stop from a gradient (minimum 2 stops enforced).
 */
export function removeStop(
  gradient: GradientValue,
  stopId: string
): GradientValue {
  if (gradient.stops.length <= 2) return gradient;
  return {
    ...gradient,
    stops: gradient.stops.filter((s) => s.id !== stopId),
  };
}

/**
 * Update a stop's properties.
 */
export function updateStop(
  gradient: GradientValue,
  stopId: string,
  updates: Partial<GradientStop>
): GradientValue {
  return {
    ...gradient,
    stops: gradient.stops.map((s) =>
      s.id === stopId ? { ...s, ...updates } : s
    ),
  };
}

/**
 * Create a default gradient of the specified type.
 */
export function createDefaultGradient(
  type: GradientValue["type"] = "linear"
): GradientValue {
  const base: GradientValue = {
    type,
    stops: [
      createGradientStop("#000000", 0),
      createGradientStop("#ffffff", 100),
    ],
  };

  switch (type) {
    case "linear":
      return { ...base, angle: 90 };
    case "radial":
      return { ...base, centerX: 50, centerY: 50 };
    case "conic":
      return { ...base, angle: 0, centerX: 50, centerY: 50 };
    case "mesh":
      return {
        ...base,
        stops: [
          { ...base.stops[0]!, x: 25, y: 25 },
          { ...base.stops[1]!, x: 75, y: 75 },
        ],
      };
    default:
      return base;
  }
}
GRADUTIL
    success "Created packages/react/src/utils/gradient.ts"
  fi

  # utils/css.ts
  if [ ! -f packages/react/src/utils/css.ts ]; then
    info "Creating packages/react/src/utils/css.ts..."
    cat > packages/react/src/utils/css.ts <<'CSSUTIL'
import type { ColorPickerValue, GradientValue, SolidColor } from "../types";
import { sortStops } from "./gradient";

/**
 * Type guard: is the value a gradient?
 */
export function isGradient(value: ColorPickerValue): value is GradientValue {
  return typeof value === "object" && value !== null && "type" in value && "stops" in value;
}

/**
 * Type guard: is the value a solid color?
 */
export function isSolidColor(value: ColorPickerValue): value is SolidColor {
  return typeof value === "string";
}

/**
 * Convert a structured ColorPickerValue to a CSS string.
 */
export function toCSS(value: ColorPickerValue): string {
  if (isSolidColor(value)) {
    return value;
  }

  const sorted = sortStops(value.stops);
  const stopsCSS = sorted
    .map((stop) => `${stop.color} ${stop.position}%`)
    .join(", ");

  switch (value.type) {
    case "linear":
      return `linear-gradient(${value.angle ?? 90}deg, ${stopsCSS})`;

    case "radial":
      return `radial-gradient(circle at ${value.centerX ?? 50}% ${value.centerY ?? 50}%, ${stopsCSS})`;

    case "conic":
      return `conic-gradient(from ${value.angle ?? 0}deg at ${value.centerX ?? 50}% ${value.centerY ?? 50}%, ${stopsCSS})`;

    case "mesh":
      // Mesh gradients are simulated as layered radial gradients
      return value.stops
        .map(
          (stop) =>
            `radial-gradient(circle at ${stop.x ?? 50}% ${stop.y ?? 50}%, ${stop.color} 0%, transparent 50%)`
        )
        .join(", ");

    default:
      return stopsCSS;
  }
}

/**
 * Parse a CSS gradient string into a structured ColorPickerValue.
 * Returns the raw string if it cannot be parsed as a gradient.
 */
export function fromCSS(css: string): ColorPickerValue {
  const trimmed = css.trim();

  // If it doesn't look like a gradient, return as solid color
  if (
    !trimmed.startsWith("linear-gradient") &&
    !trimmed.startsWith("radial-gradient") &&
    !trimmed.startsWith("conic-gradient")
  ) {
    return trimmed;
  }

  // TODO: Implement full CSS gradient parsing in Phase 2
  // For now, return the raw string as a solid color fallback
  return trimmed;
}
CSSUTIL
    success "Created packages/react/src/utils/css.ts"
  fi

  # utils/position.ts
  if [ ! -f packages/react/src/utils/position.ts ]; then
    info "Creating packages/react/src/utils/position.ts..."
    cat > packages/react/src/utils/position.ts <<'POSUTIL'
/**
 * Clamp a value between min and max.
 */
export function clamp(value: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, value));
}

/**
 * Get the normalized (0-1) position of a pointer event relative to an element.
 */
export function getRelativePosition(
  event: { clientX: number; clientY: number },
  element: HTMLElement
): { x: number; y: number } {
  const rect = element.getBoundingClientRect();
  return {
    x: clamp((event.clientX - rect.left) / rect.width, 0, 1),
    y: clamp((event.clientY - rect.top) / rect.height, 0, 1),
  };
}

/**
 * Calculate the angle (in degrees) from a center point to a position.
 */
export function angleFromPosition(
  x: number,
  y: number,
  centerX: number,
  centerY: number
): number {
  const radians = Math.atan2(y - centerY, x - centerX);
  const degrees = (radians * 180) / Math.PI + 90;
  return ((degrees % 360) + 360) % 360;
}
POSUTIL
    success "Created packages/react/src/utils/position.ts"
  fi

  # hooks/use-pointer-drag.ts
  if [ ! -f packages/react/src/hooks/use-pointer-drag.ts ]; then
    info "Creating packages/react/src/hooks/use-pointer-drag.ts..."
    cat > packages/react/src/hooks/use-pointer-drag.ts <<'USEDRAG'
import { useCallback, useRef, useState } from "react";
import { getRelativePosition } from "../utils/position";

interface UsePointerDragOptions {
  onDragStart?: (position: { x: number; y: number }) => void;
  onDrag: (position: { x: number; y: number }) => void;
  onDragEnd?: (position: { x: number; y: number }) => void;
}

interface UsePointerDragReturn {
  isDragging: boolean;
  handlePointerDown: (event: React.PointerEvent<HTMLElement>) => void;
}

/**
 * Hook for tracking pointer drag interactions on an element.
 * Returns normalized (0-1) positions relative to the target element.
 */
export function usePointerDrag(
  options: UsePointerDragOptions
): UsePointerDragReturn {
  const [isDragging, setIsDragging] = useState(false);
  const elementRef = useRef<HTMLElement | null>(null);
  const optionsRef = useRef(options);
  optionsRef.current = options;

  const handlePointerDown = useCallback(
    (event: React.PointerEvent<HTMLElement>) => {
      if (event.button !== 0) return; // Only primary button

      const element = event.currentTarget;
      elementRef.current = element;
      element.setPointerCapture(event.pointerId);

      const position = getRelativePosition(event, element);
      setIsDragging(true);
      optionsRef.current.onDragStart?.(position);
      optionsRef.current.onDrag(position);

      const handlePointerMove = (e: PointerEvent) => {
        if (!elementRef.current) return;
        const pos = getRelativePosition(e, elementRef.current);
        optionsRef.current.onDrag(pos);
      };

      const handlePointerUp = (e: PointerEvent) => {
        if (elementRef.current) {
          const pos = getRelativePosition(e, elementRef.current);
          optionsRef.current.onDragEnd?.(pos);
          elementRef.current.releasePointerCapture(e.pointerId);
        }
        setIsDragging(false);
        elementRef.current = null;
        document.removeEventListener("pointermove", handlePointerMove);
        document.removeEventListener("pointerup", handlePointerUp);
      };

      document.addEventListener("pointermove", handlePointerMove);
      document.addEventListener("pointerup", handlePointerUp);
    },
    []
  );

  return { isDragging, handlePointerDown };
}
USEDRAG
    success "Created packages/react/src/hooks/use-pointer-drag.ts"
  fi

  # hooks/use-color-picker.ts (placeholder)
  if [ ! -f packages/react/src/hooks/use-color-picker.ts ]; then
    info "Creating packages/react/src/hooks/use-color-picker.ts..."
    cat > packages/react/src/hooks/use-color-picker.ts <<'USECP'
import { useCallback, useMemo, useRef, useState } from "react";
import type { ColorFormat, ColorPickerValue, HSVA } from "../types";
import { detectFormat, formatColor, fromHSVA, isValidColor, toHSVA } from "../utils/color";
import { isGradient } from "../utils/css";

interface UseColorPickerOptions {
  value?: ColorPickerValue;
  defaultValue?: ColorPickerValue;
  onValueChange?: (value: ColorPickerValue) => void;
}

/**
 * Core state management hook for the color picker.
 * Maintains internal HSV state for smooth dragging without rounding artifacts.
 */
export function useColorPicker(options: UseColorPickerOptions) {
  const { value: controlledValue, defaultValue = "#000000", onValueChange } = options;

  const isControlled = controlledValue !== undefined;
  const [internalValue, setInternalValue] = useState<ColorPickerValue>(defaultValue);
  const currentValue = isControlled ? controlledValue : internalValue;

  // Internal HSVA state for smooth drag (avoids hex rounding during drag)
  const initialHSVA = useMemo(() => {
    if (typeof currentValue === "string") {
      return toHSVA(currentValue);
    }
    return { h: 0, s: 0, v: 0, a: 1 };
  }, []); // Only compute once on mount

  const [hsva, setHSVA] = useState<HSVA>(initialHSVA);
  const [format, setFormat] = useState<ColorFormat>(() =>
    typeof currentValue === "string" ? detectFormat(currentValue) : "hex"
  );

  // Sync external controlled value to internal HSVA
  const prevControlledRef = useRef(controlledValue);
  if (controlledValue !== prevControlledRef.current) {
    prevControlledRef.current = controlledValue;
    if (typeof controlledValue === "string") {
      // Only update HSVA if external value changed (not from our own update)
      const newHSVA = toHSVA(controlledValue);
      setHSVA(newHSVA);
    }
  }

  const updateValue = useCallback(
    (newValue: ColorPickerValue) => {
      if (!isControlled) {
        setInternalValue(newValue);
      }
      onValueChange?.(newValue);
    },
    [isControlled, onValueChange]
  );

  const setHue = useCallback(
    (h: number) => {
      setHSVA((prev) => {
        const next = { ...prev, h };
        updateValue(fromHSVA(next));
        return next;
      });
    },
    [updateValue]
  );

  const setSaturationValue = useCallback(
    (s: number, v: number) => {
      setHSVA((prev) => {
        const next = { ...prev, s, v };
        updateValue(fromHSVA(next));
        return next;
      });
    },
    [updateValue]
  );

  const setAlpha = useCallback(
    (a: number) => {
      setHSVA((prev) => {
        const next = { ...prev, a };
        updateValue(fromHSVA(next));
        return next;
      });
    },
    [updateValue]
  );

  const setColorFromString = useCallback(
    (input: string) => {
      if (!isValidColor(input)) return;
      const newHSVA = toHSVA(input);
      setHSVA(newHSVA);
      updateValue(input);
    },
    [updateValue]
  );

  const toggleFormat = useCallback(() => {
    setFormat((prev) => {
      const formats: ColorFormat[] = ["hex", "rgb", "hsl"];
      const idx = formats.indexOf(prev);
      return formats[(idx + 1) % formats.length]!;
    });
  }, []);

  const formattedValue = useMemo(() => {
    const hex = fromHSVA(hsva);
    return formatColor(hex, format);
  }, [hsva, format]);

  const cssValue = useMemo(() => fromHSVA(hsva), [hsva]);

  const isGradientMode = isGradient(currentValue);

  return {
    value: currentValue,
    hsva,
    format,
    formattedValue,
    cssValue,
    isGradientMode,
    setHue,
    setSaturationValue,
    setAlpha,
    setColorFromString,
    setFormat,
    toggleFormat,
    updateValue,
  };
}
USECP
    success "Created packages/react/src/hooks/use-color-picker.ts"
  fi

  # hooks/use-gradient.ts (placeholder)
  if [ ! -f packages/react/src/hooks/use-gradient.ts ]; then
    info "Creating packages/react/src/hooks/use-gradient.ts..."
    cat > packages/react/src/hooks/use-gradient.ts <<'USEGRAD'
import { useCallback, useState } from "react";
import type { GradientValue } from "../types";
import {
  addStop,
  createDefaultGradient,
  removeStop,
  updateStop,
} from "../utils/gradient";

interface UseGradientOptions {
  value?: GradientValue;
  onValueChange?: (value: GradientValue) => void;
}

/**
 * State management hook for gradient editing.
 */
export function useGradient(options: UseGradientOptions) {
  const { value, onValueChange } = options;

  const gradient = value ?? createDefaultGradient("linear");
  const [activeStopId, setActiveStopId] = useState<string | null>(
    gradient.stops[0]?.id ?? null
  );

  const update = useCallback(
    (newGradient: GradientValue) => {
      onValueChange?.(newGradient);
    },
    [onValueChange]
  );

  const handleAddStop = useCallback(
    (color: string, position: number) => {
      const updated = addStop(gradient, color, position);
      update(updated);
    },
    [gradient, update]
  );

  const handleRemoveStop = useCallback(
    (stopId: string) => {
      const updated = removeStop(gradient, stopId);
      update(updated);
      // If we removed the active stop, select the first one
      if (activeStopId === stopId) {
        setActiveStopId(updated.stops[0]?.id ?? null);
      }
    },
    [gradient, update, activeStopId]
  );

  const updateStopColor = useCallback(
    (stopId: string, color: string) => {
      const updated = updateStop(gradient, stopId, { color });
      update(updated);
    },
    [gradient, update]
  );

  const updateStopPosition = useCallback(
    (stopId: string, position: number) => {
      const updated = updateStop(gradient, stopId, { position });
      update(updated);
    },
    [gradient, update]
  );

  const setGradientType = useCallback(
    (type: GradientValue["type"]) => {
      update({ ...gradient, type });
    },
    [gradient, update]
  );

  const setAngle = useCallback(
    (angle: number) => {
      update({ ...gradient, angle });
    },
    [gradient, update]
  );

  const setCenter = useCallback(
    (centerX: number, centerY: number) => {
      update({ ...gradient, centerX, centerY });
    },
    [gradient, update]
  );

  const activeStop = gradient.stops.find((s) => s.id === activeStopId) ?? null;

  return {
    gradient,
    activeStopId,
    activeStop,
    setActiveStopId: setActiveStopId,
    addStop: handleAddStop,
    removeStop: handleRemoveStop,
    updateStopColor,
    updateStopPosition,
    setGradientType,
    setAngle,
    setCenter,
  };
}
USEGRAD
    success "Created packages/react/src/hooks/use-gradient.ts"
  fi

  # components/color-picker.tsx (root + context)
  if [ ! -f packages/react/src/components/color-picker.tsx ]; then
    info "Creating packages/react/src/components/color-picker.tsx..."
    cat > packages/react/src/components/color-picker.tsx <<'CPROOT'
import { createContext, useContext } from "react";
import type { ColorPickerProps } from "../types";
import { useColorPicker } from "../hooks/use-color-picker";

type ColorPickerContextValue = ReturnType<typeof useColorPicker>;

const ColorPickerContext = createContext<ColorPickerContextValue | null>(null);

/**
 * Hook to access the color picker context.
 * Must be used within a <ColorPicker> component.
 */
export function useColorPickerContext(): ColorPickerContextValue {
  const ctx = useContext(ColorPickerContext);
  if (!ctx) {
    throw new Error(
      "useColorPickerContext must be used within a <ColorPicker> component."
    );
  }
  return ctx;
}

/**
 * Root compound component for the color picker.
 *
 * Usage:
 * ```tsx
 * <ColorPicker value={color} onValueChange={setColor}>
 *   <ColorPicker.Trigger />
 *   <ColorPicker.Content>
 *     <ColorPicker.Area />
 *     <ColorPicker.HueSlider />
 *   </ColorPicker.Content>
 * </ColorPicker>
 * ```
 */
export function ColorPicker({
  value,
  onValueChange,
  defaultValue,
  disabled: _disabled,
  children,
}: ColorPickerProps) {
  const pickerState = useColorPicker({
    value,
    onValueChange,
    defaultValue,
  });

  return (
    <ColorPickerContext.Provider value={pickerState}>
      {children}
    </ColorPickerContext.Provider>
  );
}
CPROOT
    success "Created packages/react/src/components/color-picker.tsx"
  fi

  # components/presets.tsx (placeholder)
  if [ ! -f packages/react/src/components/presets.tsx ]; then
    info "Creating packages/react/src/components/presets.tsx..."
    cat > packages/react/src/components/presets.tsx <<'PRESETS'
/**
 * Pre-composed color picker components for common use cases.
 *
 * Import from "@markoradak/color-picker/presets"
 */

// TODO: Implement in Phase 6
// export function ColorPickerPopover() {}
// export function ColorPickerInline() {}

export {};
PRESETS
    success "Created packages/react/src/components/presets.tsx"
  fi

  # Placeholder component files
  local components=(
    "trigger"
    "content"
    "area"
    "hue-slider"
    "alpha-slider"
    "input"
    "format-toggle"
    "eye-dropper"
    "swatches"
    "gradient-editor"
    "gradient-preview"
    "gradient-stops"
  )

  for comp in "${components[@]}"; do
    local filepath="packages/react/src/components/${comp}.tsx"
    if [ ! -f "$filepath" ]; then
      cat > "$filepath" <<COMPFILE
/**
 * ColorPicker.${comp} component.
 * TODO: Implement in Phase 4/5
 */

export {};
COMPFILE
    fi
  done
  success "Created placeholder component files"

  # index.ts (public API)
  if [ ! -f packages/react/src/index.ts ]; then
    info "Creating packages/react/src/index.ts..."
    cat > packages/react/src/index.ts <<'INDEX'
// Components
export { ColorPicker, useColorPickerContext } from "./components/color-picker";

// Utilities
export { toCSS, fromCSS, isGradient, isSolidColor } from "./utils/css";
export { parseColor, formatColor, detectFormat, isValidColor, toHSVA, fromHSVA, getContrastColor } from "./utils/color";
export { createGradientStop, sortStops, addStop, removeStop, updateStop, createDefaultGradient } from "./utils/gradient";
export { clamp, getRelativePosition, angleFromPosition } from "./utils/position";

// Hooks
export { usePointerDrag } from "./hooks/use-pointer-drag";
export { useColorPicker } from "./hooks/use-color-picker";
export { useGradient } from "./hooks/use-gradient";

// Types
export type {
  SolidColor,
  ColorFormat,
  GradientStop,
  GradientValue,
  ColorPickerValue,
  ColorPickerProps,
  ColorPickerAreaProps,
  ColorPickerSliderProps,
  ColorPickerInputProps,
  ColorPickerSwatchesProps,
  ColorPickerTriggerProps,
  ColorPickerContentProps,
  HSVA,
} from "./types";
INDEX
    success "Created packages/react/src/index.ts"
  fi

  # Initial test file
  if [ ! -f packages/react/src/utils/color.test.ts ]; then
    info "Creating initial test file..."
    cat > packages/react/src/utils/color.test.ts <<'COLORTEST'
import { describe, expect, it } from "vitest";
import {
  detectFormat,
  formatColor,
  fromHSVA,
  getContrastColor,
  isValidColor,
  toHSVA,
} from "./color";

describe("color utilities", () => {
  describe("isValidColor", () => {
    it("validates hex colors", () => {
      expect(isValidColor("#ff0000")).toBe(true);
      expect(isValidColor("#f00")).toBe(true);
      expect(isValidColor("#ff000080")).toBe(true);
    });

    it("validates rgb colors", () => {
      expect(isValidColor("rgb(255, 0, 0)")).toBe(true);
      expect(isValidColor("rgba(255, 0, 0, 0.5)")).toBe(true);
    });

    it("validates hsl colors", () => {
      expect(isValidColor("hsl(0, 100%, 50%)")).toBe(true);
    });

    it("rejects invalid colors", () => {
      expect(isValidColor("not-a-color")).toBe(false);
      expect(isValidColor("#gggggg")).toBe(false);
    });
  });

  describe("detectFormat", () => {
    it("detects hex format", () => {
      expect(detectFormat("#ff0000")).toBe("hex");
    });

    it("detects rgb format", () => {
      expect(detectFormat("rgb(255, 0, 0)")).toBe("rgb");
      expect(detectFormat("rgba(255, 0, 0, 0.5)")).toBe("rgb");
    });

    it("detects hsl format", () => {
      expect(detectFormat("hsl(0, 100%, 50%)")).toBe("hsl");
    });
  });

  describe("formatColor", () => {
    it("converts to hex", () => {
      expect(formatColor("rgb(255, 0, 0)", "hex")).toBe("#ff0000");
    });

    it("converts to rgb", () => {
      expect(formatColor("#ff0000", "rgb")).toBe("rgb(255, 0, 0)");
    });

    it("converts to hsl", () => {
      expect(formatColor("#ff0000", "hsl")).toBe("hsl(0, 100%, 50%)");
    });
  });

  describe("toHSVA / fromHSVA roundtrip", () => {
    it("roundtrips a color", () => {
      const original = "#ff0000";
      const hsva = toHSVA(original);
      expect(hsva.h).toBe(0);
      expect(hsva.s).toBe(100);
      expect(hsva.v).toBe(100);
      expect(hsva.a).toBe(1);

      const result = fromHSVA(hsva);
      expect(result).toBe("#ff0000");
    });
  });

  describe("getContrastColor", () => {
    it("returns black for light backgrounds", () => {
      expect(getContrastColor("#ffffff")).toBe("black");
      expect(getContrastColor("#ffff00")).toBe("black");
    });

    it("returns white for dark backgrounds", () => {
      expect(getContrastColor("#000000")).toBe("white");
      expect(getContrastColor("#000080")).toBe("white");
    });
  });
});
COLORTEST
    success "Created color utility tests"
  fi

  if [ ! -f packages/react/src/utils/css.test.ts ]; then
    cat > packages/react/src/utils/css.test.ts <<'CSSTEST'
import { describe, expect, it } from "vitest";
import { isGradient, isSolidColor, toCSS } from "./css";
import type { GradientValue } from "../types";

describe("css utilities", () => {
  describe("type guards", () => {
    it("identifies solid colors", () => {
      expect(isSolidColor("#ff0000")).toBe(true);
      expect(isSolidColor("rgb(255, 0, 0)")).toBe(true);
    });

    it("identifies gradients", () => {
      const gradient: GradientValue = {
        type: "linear",
        angle: 90,
        stops: [
          { id: "1", color: "#000", position: 0 },
          { id: "2", color: "#fff", position: 100 },
        ],
      };
      expect(isGradient(gradient)).toBe(true);
      expect(isGradient("#ff0000")).toBe(false);
    });
  });

  describe("toCSS", () => {
    it("returns solid colors as-is", () => {
      expect(toCSS("#ff0000")).toBe("#ff0000");
    });

    it("generates linear gradient CSS", () => {
      const gradient: GradientValue = {
        type: "linear",
        angle: 90,
        stops: [
          { id: "1", color: "#000", position: 0 },
          { id: "2", color: "#fff", position: 100 },
        ],
      };
      expect(toCSS(gradient)).toBe(
        "linear-gradient(90deg, #000 0%, #fff 100%)"
      );
    });

    it("generates radial gradient CSS", () => {
      const gradient: GradientValue = {
        type: "radial",
        centerX: 50,
        centerY: 50,
        stops: [
          { id: "1", color: "red", position: 0 },
          { id: "2", color: "blue", position: 100 },
        ],
      };
      expect(toCSS(gradient)).toBe(
        "radial-gradient(circle at 50% 50%, red 0%, blue 100%)"
      );
    });

    it("generates conic gradient CSS", () => {
      const gradient: GradientValue = {
        type: "conic",
        angle: 0,
        centerX: 50,
        centerY: 50,
        stops: [
          { id: "1", color: "red", position: 0 },
          { id: "2", color: "blue", position: 100 },
        ],
      };
      expect(toCSS(gradient)).toBe(
        "conic-gradient(from 0deg at 50% 50%, red 0%, blue 100%)"
      );
    });
  });
});
CSSTEST
    success "Created CSS utility tests"
  fi

  success "Library scaffold complete"
}

# -- Demo Site (apps/web/) ----------------------------------------------------

scaffold_demo_site() {
  header "Scaffolding apps/web/ (Next.js demo site)..."

  mkdir -p apps/web/{app,components,public}
  mkdir -p apps/web/app/playground

  # package.json
  if [ ! -f apps/web/package.json ]; then
    info "Creating apps/web/package.json..."
    cat > apps/web/package.json <<'WEBPKG'
{
  "name": "web",
  "private": true,
  "version": "0.0.1",
  "scripts": {
    "dev": "next dev --turbopack",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "typecheck": "tsc --noEmit"
  },
  "dependencies": {
    "@markoradak/color-picker": "workspace:*",
    "next": "^15.2.0",
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  },
  "devDependencies": {
    "@tailwindcss/postcss": "^4.0.0",
    "@types/node": "^22.0.0",
    "@types/react": "^19.0.0",
    "@types/react-dom": "^19.0.0",
    "postcss": "^8.5.0",
    "tailwindcss": "^4.0.0",
    "typescript": "^5.7.0"
  }
}
WEBPKG
    success "Created apps/web/package.json"
  fi

  # tsconfig.json
  if [ ! -f apps/web/tsconfig.json ]; then
    info "Creating apps/web/tsconfig.json..."
    cat > apps/web/tsconfig.json <<'WEBTS'
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "plugins": [{ "name": "next" }],
    "module": "ESNext",
    "moduleResolution": "bundler",
    "allowJs": true,
    "jsx": "preserve",
    "incremental": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    ".next/types/**/*.ts"
  ],
  "exclude": ["node_modules"]
}
WEBTS
    success "Created apps/web/tsconfig.json"
  fi

  # next.config.ts
  if [ ! -f apps/web/next.config.ts ]; then
    info "Creating apps/web/next.config.ts..."
    cat > apps/web/next.config.ts <<'NEXTCFG'
import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  transpilePackages: ["@markoradak/color-picker"],
};

export default nextConfig;
NEXTCFG
    success "Created apps/web/next.config.ts"
  fi

  # postcss.config.mjs (Tailwind v4)
  if [ ! -f apps/web/postcss.config.mjs ]; then
    info "Creating apps/web/postcss.config.mjs..."
    cat > apps/web/postcss.config.mjs <<'POSTCSS'
const config = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};

export default config;
POSTCSS
    success "Created apps/web/postcss.config.mjs"
  fi

  # app/globals.css (Tailwind v4)
  if [ ! -f apps/web/app/globals.css ]; then
    info "Creating apps/web/app/globals.css..."
    cat > apps/web/app/globals.css <<'GLOBALCSS'
@import "tailwindcss";
GLOBALCSS
    success "Created apps/web/app/globals.css"
  fi

  # app/layout.tsx
  if [ ! -f apps/web/app/layout.tsx ]; then
    info "Creating apps/web/app/layout.tsx..."
    cat > apps/web/app/layout.tsx <<'LAYOUT'
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "@markoradak/color-picker",
  description:
    "A compound-component React color picker and gradient editor library",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-white text-neutral-900 antialiased dark:bg-neutral-950 dark:text-neutral-100">
        {children}
      </body>
    </html>
  );
}
LAYOUT
    success "Created apps/web/app/layout.tsx"
  fi

  # app/page.tsx
  if [ ! -f apps/web/app/page.tsx ]; then
    info "Creating apps/web/app/page.tsx..."
    cat > apps/web/app/page.tsx <<'PAGE'
export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center gap-8 p-8">
      <div className="text-center">
        <h1 className="text-4xl font-bold tracking-tight">
          @markoradak/color-picker
        </h1>
        <p className="mt-4 text-lg text-neutral-600 dark:text-neutral-400">
          A compound-component React color picker and gradient editor.
        </p>
      </div>

      <div className="rounded-xl border border-neutral-200 bg-neutral-50 p-8 dark:border-neutral-800 dark:bg-neutral-900">
        <p className="text-sm text-neutral-500">
          Color picker component will render here once implemented.
        </p>
      </div>

      <div className="flex gap-4">
        <a
          href="/playground"
          className="rounded-lg bg-neutral-900 px-6 py-3 text-sm font-medium text-white transition-colors hover:bg-neutral-800 dark:bg-white dark:text-neutral-900 dark:hover:bg-neutral-200"
        >
          Open Playground
        </a>
      </div>
    </main>
  );
}
PAGE
    success "Created apps/web/app/page.tsx"
  fi

  # app/playground/page.tsx
  if [ ! -f apps/web/app/playground/page.tsx ]; then
    info "Creating apps/web/app/playground/page.tsx..."
    cat > apps/web/app/playground/page.tsx <<'PLAYGROUND'
export default function PlaygroundPage() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center gap-8 p-8">
      <h1 className="text-3xl font-bold">Playground</h1>
      <p className="text-neutral-600 dark:text-neutral-400">
        Interactive color picker configurator coming soon.
      </p>
    </main>
  );
}
PLAYGROUND
    success "Created apps/web/app/playground/page.tsx"
  fi

  success "Demo site scaffold complete"
}

# -- Install Dependencies ------------------------------------------------------

install_dependencies() {
  header "Installing dependencies..."

  info "Running pnpm install (this may take a moment)..."
  pnpm install

  success "Dependencies installed"
}

# -- Install Root Dev Dependencies ---------------------------------------------

install_root_devdeps() {
  header "Installing root dev dependencies..."

  pnpm add -Dw turbo typescript

  success "Root dev dependencies installed"
}

# -- Verify Build --------------------------------------------------------------

verify_build() {
  header "Verifying build pipeline..."

  info "Building library with tsup..."
  pnpm --filter @markoradak/color-picker build

  if [ -d packages/react/dist ]; then
    success "Library built successfully (packages/react/dist/)"
  else
    warn "Library build may have failed -- dist/ directory not found"
  fi
}

# -- Run Tests -----------------------------------------------------------------

run_tests() {
  header "Running initial tests..."

  pnpm --filter @markoradak/color-picker test || {
    warn "Some tests failed. This is expected for placeholder tests."
  }
}

# -- Main ----------------------------------------------------------------------

main() {
  echo ""
  echo "========================================"
  echo "  Bootstrapping: @markoradak/color-picker"
  echo "========================================"
  echo ""
  echo "This script will set up a pnpm monorepo with:"
  echo "  - packages/react/  -- Component library (tsup, vitest)"
  echo "  - apps/web/        -- Next.js demo site (Tailwind v4)"
  echo "  - Turborepo for task orchestration"
  echo ""

  # Prerequisites
  check_node
  check_pnpm

  echo ""
  read -p "Continue with bootstrap? (y/n) " -n 1 -r
  echo ""
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    warn "Bootstrap cancelled."
    exit 0
  fi

  echo ""

  # Step 1: Root configuration
  header "Step 1/7: Root workspace configuration"
  create_root_package_json
  create_pnpm_workspace
  create_npmrc
  create_turbo_json
  create_root_tsconfig
  create_gitignore

  # Step 2: Library scaffold
  header "Step 2/7: Library package"
  scaffold_library

  # Step 3: Demo site scaffold
  header "Step 3/7: Demo site"
  scaffold_demo_site

  # Step 4: Root dev deps
  header "Step 4/7: Root dependencies"
  install_root_devdeps

  # Step 5: Install all deps
  header "Step 5/7: Install all dependencies"
  install_dependencies

  # Step 6: Verify build
  header "Step 6/7: Verify build"
  verify_build

  # Step 7: Run tests
  header "Step 7/7: Run tests"
  run_tests

  # Summary
  echo ""
  echo "========================================"
  echo ""
  success "Bootstrap complete!"
  echo ""
  echo "  Project structure:"
  echo "    packages/react/    @markoradak/color-picker (library)"
  echo "    apps/web/          Next.js demo/docs site"
  echo ""
  echo "  Available commands:"
  echo "    pnpm dev           Start dev servers (library + web)"
  echo "    pnpm build         Build everything"
  echo "    pnpm test          Run tests"
  echo "    pnpm typecheck     Type-check all packages"
  echo ""
  echo "  Next steps:"
  echo "    1. Review tasks/plans/PLAN_00_INITIAL.md for the full implementation plan"
  echo "    2. Start with Phase 2 -- core types and color utilities are scaffolded"
  echo "    3. Run 'pnpm dev' to start development"
  echo ""
}

main
